language: android
jdk: oraclejdk8
sudo: required
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
    - GITHUB_TOKEN=7f09e35a5b611169509357ee1c8208c6001e4ffa
    - REPO=dajandro/MedLine-Pruebas
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-15
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
before_install:
 - chmod +x gradlew
script:
  - ./gradlew build connectedCheck
deploy:
  provider: pages
  github_token: ${GITHUB_TOKEN}
  on:
    repo: ${REPO}