language: android
jdk: oraclejdk8
sudo: true
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
    - GITHUB_TOKEN=7f09e35a5b611169509357ee1c8208c6001e4ffa
    - REPO=dajandro/MedLine-Pruebas
script:
   - sudo ./gradlew tasks
deploy:
  provider: pages
  github_token: ${GITHUB_TOKEN}
  on:
    repo: ${REPO}